name: ledger_lib_dart
description: Ledger dart library for Flutter (web mode). This library aims to provide a easy way to communicate with Ledger Nano S key based on HID Protocol)
homepage: https://github.com/reddwarf03/ledger_dart_lib

version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:

  # Utilities for converting between data representations. Provides a number of Sink, Codec, Decoder, and Encoder types
  convert: ^3.0.1

  # Dart wrapper via dart:js for https://wicg.github.io/webhid/
  web_hid: ^0.2.1+1

dev_dependencies:
  flutter_lints: ^1.0.4
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  test: ^1.19.5