name: ledger_dart_lib
description: Ledger dart library for Flutter. This library aims to provide a easy way to communicate with Ledger devices.
homepage: https://github.com/reddwarf03/ledger_dart_lib

version: 0.1.4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:

  # Utilities for converting between data representations. Provides a number of Sink, Codec, Decoder, and Encoder types
  convert: ^3.0.1

  flutter:
    sdk: flutter

  # Dart wrapper via dart:js for https://wicg.github.io/webhid/
  web_hid: ^0.2.1+1

  # A multi-platform plugin which allows an application to interface with USB HID-Class devices on Linux, Windows, Android, and macOS.
  hid: ^0.1.6

dev_dependencies:
  flutter_lints: ^1.0.4
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  test: ^1.19.5